# docker-compose.yml
version: '3.8'

services:
  app:
    image: shenlongcodes/portfolio:latest
    container_name: portfolio-app
    restart: unless-stopped
    ports:
      - "3000:3000"

  # The Prometheus Scraper
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      # Expose Nginx on port 3001
      - "3001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./.htpasswd:/etc/nginx/.htpasswd

volumes:
  grafana-data: