name: Deploy to DigitalOcean

on:
  push:
    branches: [ "main" ]  # triggers only when pushing to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout your repo
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Build and push Docker image
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/portfolio:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/portfolio:latest

      # SSH into Droplet and deploy
      - name: Deploy on Droplet
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DO_SSH_HOST }}
          username: ${{ secrets.DO_SSH_USER }}
          key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker stop portfolio || true
            docker rm portfolio || true
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/portfolio:latest
            docker ps
            docker run -d -p 80:3000 --name portfolio ${{ secrets.DOCKERHUB_USERNAME }}/portfolio:latest
            docker ps
            
      - name: Run Datadog Agent container
        run: |
          docker run -d --name datadog-agent \
            -e DD_API_KEY=${{ secrets.DATADOG_API_KEY }} \
            -e DD_SITE="datadoghq.com" \
            -e DD_LOGS_ENABLED=true \
            -v /var/run/docker.sock:/var/run/docker.sock:ro \
            datadog/agent:latest